language: node_js
cache: yarn
before_deploy:
  - openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv
    -in travis.env.enc -out .env -d
deploy:
  provider: firebase
  token:
    secure: 'Ml/FfQtcptL1FaeKxweAl6/hj5hwA/QH9eqZLWJ2jxJqkeK5jqz5ZAbpDA7pvo0XH4p5gxe7uk+SHS/hNcEW4QyK4Hg1ijOYefbf9yhqZY7e3VchuSe/G+Tmp+iy7EtNhBtIdHzCFk9j9v+Ib80hUj0h49CTtrzv78wsPOnHs5rX+V34VN6kUnn8FVPwUPo7SqqQLjRBHGja9+aPhNUVvvB+mP4sH1JDJ93MlMQKICCk/KRFKxegq34u+7jlB61ihRd2SEZFioPrKSV6bY9vnQuqR5O0xL2s0snQ9NB7TbF8NKrZ/iutzk90D7lv9wEbZTor3RLfDVR0yd2mrLVjr8Ve8gSnKKyv/nNgwvnp4Kle3Zt8XnsuC+YegHupRvSLACr4YMkstsw/76RbjJA6fFOdoxj+LFO8UCieBOkEQhe7KYfy+vPun6TvAD2ZJV20JZeqs05MDQfCH5o7v2rhvJoiYyvPmNRiJzOl6jvtvme1TrZDxm09AYgztKgzQmA0Jext8ynI9sG+yGcIikPfRzlTqO3th/YY1nQcp6mzenO6k4I1iI+lTGZj532pL0iZThJQ7cGP++qMr0/WgcPv08dKm3mwM1wHLMKRx2Q6HRBRFRQoZ6pnARYeFKf+GLFUzMHYa9MUYfthcdPPpRwglL0J/g0tK6YZnjEsEWrkEmY='
  project: feeder-88e0a
  skip_cleanup: true
  on:
    branch: master
